### ISSUE TITLE
TypeReader parts as NuGet package

### ISSUE THREAD

**Issue by vidstige** [LayoutFarm/FontRasterizer#2]
I think it would be best to try to move out the ttf loader parts into a library, then you can just add a dependency from PixelFarm on that.

**Comment by prepare** [comment]
yes, for the current version:

    1. OpenTypeReader => is just a dll, depends on System dll only (for load font), 
       it's not depend on PixelFarm***

    2. for the Sample.WinForms : I read data from opentype font by using  OpenTypeReader.
      and send the vertice data to PixelFarm to render it -> and copy pixel to System.Bitmap.

If I don't understand your question, please explain more :)

**Comment by prepare** [comment]
just update, for more flexible path builder mechanism.

see 112590ed92bc6595fe73d17c741b615c85d968ac,

     just inherit from GlyphBuilderBase,
     and implement your own VertexBuilder.

     this example shows 2 GlyphPathBuilder Implementation
     1. GlyphPathBuilderVxs : build with MiniAgg
     2. GlyphPathBuilderGdiPlus: build with System.Drawing.Drawing2D.GraphicsPath

**Comment by vidstige** [comment]
Looks great! What I mean this should go into the NRasterizer repo instead. I can also change the name to NOpenType or something. Then you could slurp NOpenType as a NuGet dependency in PixelFarm. Hope this makes sense.

**Comment by prepare** [comment]
@vidstige ,

I'm happy with your choice. :)
If you want to make the Nuget -> lets do it 👍 


----

> What I mean this should go into the NRasterizer repo instead. 

Should I send you a pull request ?

:)

**Comment by vidstige** [comment]
Sure send! I'll clean up things afterwards. :+1: I'll make the NuGet aswell. As you added me as contributor I can probably make the change here aswell. :-)

**Comment by vidstige** [comment]
I'll make a few commits first - Moving out the reader parts etc to its own project.

**Comment by prepare** [comment]
> As you added me as contributor I can probably make the change here aswell. :-)
Lets do it.

**Comment by prepare** [comment]
I just send you a pull request.
I remove PixelFarm's MiniAgg.
The sample is on WindowsForms and use GraphicsPath 
for rendering reference.

**Comment by vidstige** [comment]
You need .NET 2.0 for some reason?

**Comment by prepare** [comment]
yes, still need for a while
for my user machines (many).

**Comment by vidstige** [comment]
I see. Let's go for .NET 2.0 in the `NOpenType` project then!

**Comment by vidstige** [comment]
I'm on my Mac right now. Can you make a pull request against current master _only_ downgrading to 2.0? I like to do things in steps :-)

**Comment by vidstige** [comment]
Out of curiosity what project are you using PixelFarm for? Or do you mean library users? How many users do you have?

**Comment by vidstige** [comment]
I'm currently adding a simple command line program that I will use to create example renders on current master on each build.. :-)

**Comment by prepare** [comment]
> Can you make a pull request against current master only downgrading to 2.0? I like to do things in steps 

OK,
but today is very busy,
I'll try

**Comment by prepare** [comment]
> what project are you using PixelFarm for? Or do you mean library users? How many users do you have?

PixelFarm is backend of the HtmlRenderer (https://github.com/prepare/HTML-Renderer).
the HtmlRenderer power my app,

for user about 1000-1500 machines.
and I can't update all those machines,
some still run with WinXP
:)

**Comment by vidstige** [comment]
One more question, if you have `System.Drawing` why don't you simply use the [`DrawString` ](https://msdn.microsoft.com/en-us/library/system.drawing.graphics.drawstring(v=vs.110).aspx) method?

**Comment by prepare** [comment]
the HtmlRenderer will go cross platform (It has some 
part that will run on .NETCore).
but PixelFarm's hardware-based (based on OpenGLES2 via Angle project)
for text rendering is not complete.

for the current version, we use FreeType.  
But I think if I  can read font directly from C#, It will give
me more flexibility.

**Comment by vidstige** [comment]
One more question, you're using the names `Curve3`and `Curve4`. What is the difference between those two?

**Comment by prepare** [comment]
Yes, It what then GlyphPathBuilder found the data in the glyph.

( see http://stackoverflow.com/questions/18814022/what-is-the-difference-between-cubic-bezier-and-quadratic-bezier-and-their-use-c)

Curve3 =>   quadratic curve ,
       use 3 points to generate curve,
              (x1,y1) // previous latest draw point 
              (c1,y1) // 1 curve-control-point
              (x2,y2) // latest draw point

Curve4=>   quadratic curve ,
       use 4 points to generate curve,
              (x1,y1) // previous latest draw point 
              (cx1,cy1) // 1st curve-control-point
              (cx2,cy2) // 2nd curve-control-point
              (x2,y2) // latest draw point

In Gdi+, you need to convert Curve3 to Curve4 before send to GraphicPath

//from http://stackoverflow.com/questions/9485788/convert-quadratic-curve-to-cubic-curve
           
          //Control1X = StartX + (.66 * (ControlX - StartX))
            //Control2X = EndX + (.66 * (ControlX - EndX))


            float c1x = lastX + (float)((2f / 3f) * (p2x - lastX));
            float c1y = lastY + (float)((2f / 3f) * (p2y - lastY));
            //---------------------------------------------------------------------
            float c2x = (float)(x + ((2f / 3f) * (p2x - x)));
            float c2y = (float)(y + ((2f / 3f) * (p2y - y)));
            //---------------------------------------------------------------------
            ps.AddBezier(
                new PointF(lastX, lastY),
                new PointF(c1x, c1y),
                new PointF(c2x, c2y),
                new PointF(lastX = (float)x, lastY = (float)y));

**Comment by vidstige** [comment]
I tried to clone and build your solution, but it didn't work on MonoDevelop (mac). I'll make the NuGet package and then you can use that. :+1:

**Comment by vidstige** [comment]
Alright, I've got a NuGet package. But I cannot upload to nuget right now for some reason... Can I send it on mail?
